db:
  postgresql:
    address: "127.0.0.1:5432"
    username: "weasel"
    password: "qwr123rrr"
    database: "eve"

#  mongodb:
#    address: "192.168.1.56"
#    username: ""
#    password: ""
#    database: "service_logs"

redis:
  host:   "192.168.1.211"
  port:   6381
  db:     10

path:
  templates: "templates/html" #Path to templates
  static: "/srv/src/static" #Path to static
  HTTPStatic: "assets" #Static will be served on this http path
  ImageStatic: "images" #Statics, that are not included in bindata

esi: "https://esi.tech.ccp.is/latest/"

session-timeout: 2592000 #session expiration in seconds

memcached: "127.0.0.1:11211"